version: "3.7"
services:
  app:
    build:
      context: ./docker/nim
      dockerfile: Dockerfile
    tty: true
    privileged: true
    volumes:
      - ./workspace:/opt/nim-sample
    working_dir: /opt/nim-sample
